#!/usr/bin/env python3
"""Prepares the colour switch of an InDesign report from the origin spectrum rule to the
current one: a recolour mapping for its SVG links, an InDesign script updating the named
swatches, and an inventory of what does not belong to the spectrum.

Usage: bascule-rapport.py <report.idml> <links-dir> [--cmjn]
Writes exports/spectre/bascule-rapport/: svg-recolore.txt, inventaire.md and nuances-indesign-rvb.jsx,
or nuances-indesign-cmjn.jsx with --cmjn (FOGRA39 separations from exports/spectre/epreuve-cmjn.csv).
"""
import argparse
import csv
import re
import zipfile
from collections import Counter
from pathlib import Path
from urllib.parse import unquote
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "exports/spectre/bascule-rapport"

# Recipe swatches ("bien · canard 600") are retargeted by their usage name to the acted
# recipe and renamed accordingly. Same table as USAGES in notebooks/lib/ase.js.
RECETTES = {
    "mal": ("coquelicot", "500"), "plutôt mal": ("ambre", "200"),
    "plutôt bien": ("canard", "300"), "bien": ("canard", "550"),
    "ça dépend (pivot)": ("ardoise", "100"), "ne sait pas": ("ardoise", "100"),
    "oui": ("canard", "550"), "non": ("coquelicot", "500"),
    "milieu (3 états)": ("ambre", "300"),
    "jamais": ("petrole", "100"), "parfois": ("petrole", "400"),
    "souvent": ("petrole", "550"), "très fréquemment": ("petrole", "700"),
    "catégorie 1": ("coquelicot", "500"), "catégorie 2": ("canard", "450"),
    "catégorie 3": ("ambre", "400"), "catégorie 4": ("lavande", "300"),
    "catégorie 5": ("framboise", "600"), "catégorie 6": ("prairie", "300"),
}


def read_csv(path):
    return {(r["famille"], r["palier"]): r for r in csv.DictReader(open(path))}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("idml", type=Path)
    ap.add_argument("links", type=Path)
    ap.add_argument("--cmjn", action="store_true")
    args = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)

    origin = read_csv(ROOT / "exports/spectre/variantes/ecretage-srgb.csv")
    current = read_csv(ROOT / "exports/spectre/spectre-nsp.csv")
    cmjn = read_csv(ROOT / "exports/spectre/epreuve-cmjn.csv") if args.cmjn else {}
    by_hex_origin = {}
    for key, r in origin.items():
        by_hex_origin.setdefault(r["hex"].upper(), key)

    # SVG links: every hex, matched to the origin spectrum
    counts = Counter()
    for svg in sorted(args.links.glob("*.svg")):
        counts.update(h.upper() for h in re.findall(r"#[0-9a-fA-F]{6}", svg.read_text(errors="ignore")))
    mapping, unchanged, foreign = [], [], []
    for hex_, n in counts.most_common():
        key = by_hex_origin.get(hex_)
        if key is None:
            foreign.append((hex_, n))
        elif current[key]["hex"].upper() != hex_:
            mapping.append((hex_, current[key]["hex"].upper(), key, n))
        else:
            unchanged.append((hex_, key, n))
    (OUT / "svg-recolore.txt").write_text("".join(f"{a}:{b}\n" for a, b, _, _ in mapping))

    # InDesign swatches named after a spectrum step ("petrole 700", "bien · canard 600")
    graphic = ET.fromstring(zipfile.ZipFile(args.idml).read("Resources/Graphic.xml"))
    swatches, renamed = [], []
    for c in graphic.iter("Color"):
        name = unquote(c.get("Name", ""))
        base, _, suffix = name.partition(" copie")
        m = re.search(r"([a-z]+) (\d{2,3})$", base)
        if not m or (m.group(1), m.group(2)) not in current:
            continue
        key = (m.group(1), m.group(2))
        usage = base[: m.start()].rstrip(" ·")
        new_name = name
        if usage in RECETTES:
            key = RECETTES[usage]
            new_name = f"{usage} · {key[0]} {key[1]}" + (" copie" + suffix if _ else "")
            if new_name != name:
                renamed.append((name, new_name))
        if args.cmjn:
            r = cmjn.get(key)
            if not r:
                continue
            swatches.append((name, new_name, "CMYK", [int(r["C"]), int(r["M"]), int(r["Y"]), int(r["K"])]))
        else:
            h = current[key]["hex"]
            swatches.append((name, new_name, "RGB", [int(h[i:i + 2], 16) for i in (1, 3, 5)]))
    lines = ",\n".join(f'  ["{n}", "{nn}", "{sp}", [{", ".join(map(str, v))}]]' for n, nn, sp, v in swatches)
    (OUT / ("nuances-indesign-cmjn.jsx" if args.cmjn else "nuances-indesign-rvb.jsx")).write_text(f"""// Updates the named spectrum swatches of the active InDesign document
// ({"CMYK separations, Coated FOGRA39" if args.cmjn else "RGB values of the current spectrum"}).
// Generated by scripts/bascule-rapport.py. Run: Window > Utilities > Scripts, then double-click.
var entries = [
{lines}
];
var doc = app.activeDocument, done = 0, missing = [];
for (var i = 0; i < entries.length; i++) {{
  var sw = doc.colors.itemByName(entries[i][0]);
  if (!sw.isValid) {{ missing.push(entries[i][0]); continue; }}
  sw.model = ColorModel.PROCESS;
  sw.space = entries[i][2] === "CMYK" ? ColorSpace.CMYK : ColorSpace.RGB;
  sw.colorValue = entries[i][3];
  if (entries[i][1] !== entries[i][0]) sw.name = entries[i][1];
  done++;
}}
alert(done + " nuances mises à jour" + (missing.length ? "\\nIntrouvables : " + missing.join(", ") : ""));
""")

    # Inventory
    md = ["# Bascule du rapport vers le spectre courant\n", f"Liens SVG analysés : {len(list(args.links.glob('*.svg')))}. Nuances InDesign reconnues : {len(swatches)}.\n"]
    md.append("\n## Couleurs des SVG à remplacer (`svg-recolore.txt`)\n\n| Ancienne | Nouvelle | Palier | Occurrences |\n|---|---|---|---|\n")
    md += [f"| `{a}` | `{b}` | {k[0]} {k[1]} | {n} |\n" for a, b, k, n in mapping]
    md.append("\n## Couleurs du spectre inchangées\n\n")
    md += [f"- `{h}` {k[0]} {k[1]} ({n} occurrences)\n" for h, k, n in unchanged]
    md.append("\n## Couleurs hors spectre dans les SVG\n\nGris de thème svglite (grille, axes, texte) et palettes par défaut de ggplot : à traiter à part, elles ne suivent aucun palier.\n\n")
    md += [f"- `{h}` ({n} occurrences)\n" for h, n in foreign]
    md.append("\n## Nuances InDesign de recette réalignées sur la palette actée (et renommées)\n\n")
    md += [f"- {a} → {b}\n" for a, b in renamed]
    md.append(f"\n## Nuances InDesign reconnues ({len(swatches)}, mises à jour par les scripts `.jsx`)\n\n")
    md += [f"- {n}\n" for n, _, _, _ in swatches]
    (OUT / "inventaire.md").write_text("".join(md))
    print(f"{len(mapping)} couleurs SVG à remplacer, {len(unchanged)} inchangées, {len(foreign)} hors spectre ; {len(swatches)} nuances InDesign")


if __name__ == "__main__":
    main()
