// Catalogue des graphiques à barres empilées : pour chaque graphique, le fichier de Links à remplacer,
// la largeur du bloc de destination, le jeu de réponses et les groupes de modalités dans l'ordre d'affichage.
// Une modalité s'écrit [clé dans le CSV, libellé affiché] ; le libellé est facultatif s'il est identique à la clé.

const VERSANT = ["FPE", "FPT", "FPH"];
const AGE = [["0-34", "<35"], ["35-44"], ["45-54"], ["55+"]];
const CATEGORIE = [["A+"], ["A"], ["B"], ["C"], ["Autre"]];
const ENCADREMENT = [["Oui tâche principale"], ["Oui tâche secondaire"], ["Non"]];
const SEXE = [["Homme"], ["Femme"]];
const LONGEVITE = [["[0;2["], ["[3;9["], ["[10;19["], ["[20;+["]];
const TELETRAVAIL = [["Jamais"], ["<1j/s", "< 1 j/s"], ["1j/s", "1 j/s"], ["2j/s", "2 j/s"], ["3j/s et +", "3 j/s et +"]];
const TURNOVER = [["Trop faible"], ["Comme il faut"], ["Trop important"]];
const OUI_NON = [["Oui"], ["Non"]];
const FREQ4 = [["Très fréquemment"], ["Souvent"], ["Parfois"], ["Jamais"]];
const REUNIONS = [["Au moins une fois par semaine"], ["Au moins une fois par mois"], ["Au moins une fois tous les 6 mois"], ["Une fois par an ou moins"], ["Jamais"]];
const OUI5 = [["Oui"], ["Plutôt oui"], ["Plutôt non"], ["Non"]];
const DIPLOME = [["Bac ou-", "Bac ou moins"], ["Bac+2"], ["Bac+3/4"], ["Bac+5p", "Bac+5 ou plus"]];
const ACCORD4 = [["Tout à fait d'accord", "Tout à fait d’accord"], ["Plutôt d'accord", "Plutôt d’accord"], ["Plutôt pas d'accord", "Plutôt pas d’accord"], ["Pas du tout d'accord", "Pas du tout d’accord"]];
const ENCADRANTS = [["Oui tâche principale"], ["Oui tâche secondaire"]];
const CAUSES_MANAGER = [["D’une volonté personnelle d’exercer une fonction d’encadrement"], ["D’un choix personnel contraint par des facteurs extérieurs (nécessité pour progresser professionnellement, réorganisation, titularisation dans un nouveau grade, etc.)"], ["D’un choix de l’employeur indépendant de votre volonté (réorganisation de service)"]];
const groupe = (intitule, fichier, modalites, axe = "") => ({intitule, fichier, axe, modalites: modalites.map((m) => (Array.isArray(m) ? m : [m]))});

export const JEUX = {
  bien: {reponses: ["Bien", "Plutôt bien", "Plutôt mal", "Mal", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  bonne: {reponses: ["Bonne", "Plutôt bonne", "Plutôt mauvaise", "Mauvaise", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  oui5: {reponses: ["Oui", "Plutôt oui", "Plutôt non", "Non", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  oui3: {reponses: ["Oui", "Ne sait pas ou autre", "Non"], couleurs: ["#007777", "#DE9B58", "#C24146"], blanc: [0, 2]},
  frequence: {reponses: ["Très fréquemment", "Souvent", "Parfois", "Jamais", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  // même échelle pour un fait défavorable (travailler seul) : le rouge est du côté « très fréquemment »
  frequenceNegative: {reponses: ["Très fréquemment", "Souvent", "Parfois", "Jamais", "Ne sait pas ou autre"], couleurs: ["#C24146", "#DF6263", "#EBBF95", "#007777", "#E0E7EB"], blanc: [0, 1, 3]},
  // progression pétrole 700 / 550 / 400 / 250 / 100, comme les anciens graphiques
  reunions: {reponses: ["Au moins une fois par semaine", "Au moins une fois par mois", "Au moins une fois tous les 6 mois", "Une fois par an ou moins", "Jamais", "Ne sait pas ou autre"], couleurs: ["#0B4862", "#107098", "#3C9AC8", "#7AC4EC", "#D1EBF9", "#E0E7EB"], blanc: [0, 1, 2]},
  turnover: {reponses: ["Trop faible", "Comme il faut", "Trop important", "Ne sait pas ou autre"], couleurs: ["#DF6263", "#007777", "#C24146", "#E0E7EB"], blanc: [0, 1, 2]},
  ouiNon3: {reponses: ["Oui", "Non", "Ne sait pas ou autre"], couleurs: ["#007777", "#C24146", "#E0E7EB"], blanc: [0, 1]},
  ouiNon2: {reponses: ["Oui", "Non"], couleurs: ["#007777", "#C24146"], blanc: [0, 1]},
  nonOui2: {reponses: ["Non", "Oui"], couleurs: ["#007777", "#C24146"], blanc: [0, 1]},
  accord5: {reponses: ["Tout à fait d'accord", "Plutôt d'accord", "Plutôt pas d'accord", "Pas du tout d'accord", "Ne sait pas ou autre"], libelles: ["Tout à fait d’accord", "Plutôt d’accord", "Plutôt pas d’accord", "Pas du tout d’accord", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  ouiToutAFait: {reponses: ["Oui, tout à fait", "Plutôt oui", "Plutôt non", "Non, pas du tout", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  importance: {reponses: ["Très important", "Plutôt important", "Peu important", "Pas du tout important", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146", "#E0E7EB"], blanc: [0, 3]},
  identification: {reponses: ["Oui, il s'agit d'une seule personne que vous pouvez nommer", "Vous identifiez deux personnes ou plus qui pourraient être qualifiées comme telles", "Non, vous n'identifiez personne en particulier qui pourrait correspondre", "Non, vous n'avez pas de supérieur·e hiérarchique direct·e"],
    libelles: ["Oui, il s’agit d’une seule personne que vous pouvez nommer", "Vous identifiez deux personnes ou plus qui pourraient être qualifiées comme telles", "Non, vous n’identifiez personne en particulier qui pourrait correspondre", "Non, vous n’avez pas de supérieur·e hiérarchique direct·e"],
    couleurs: ["#007777", "#32C2C2", "#EBBF95", "#C24146"], blanc: [0, 3]},
  // progression pétrole 700 / 250 pour deux manières de recevoir les indications
  indications: {reponses: ["On vous dit aussi comment il faut le faire", "On vous indique plutôt l’objectif du travail et vous choisissez vous-même la façon d’y arriver", "Ne sait pas ou autre"], couleurs: ["#0B4862", "#7AC4EC", "#E0E7EB"], blanc: [0]},
  consignes: {reponses: ["Vous appliquez strictement les consignes", "Dans certains cas, vous faites autrement", "La plupart du temps, vous faites autrement", "Ne sait pas ou autre"], couleurs: ["#0B4862", "#1C7EA9", "#7AC4EC", "#E0E7EB"], blanc: [0, 1]},
  // consignes qui dégradent le sens du travail : le rouge est du côté « très fréquemment »
  degradation: {reponses: ["Oui, très fréquemment", "Oui, souvent", "Oui, parfois", "Non, jamais", "Ne sait pas ou autre"], couleurs: ["#C24146", "#DF6263", "#EBBF95", "#007777", "#E0E7EB"], blanc: [0, 1, 3]},
  transmission: {reponses: ["Oui, souvent", "Oui, parfois", "Non", "Ne sait pas ou autre"], couleurs: ["#007777", "#32C2C2", "#C24146", "#E0E7EB"], blanc: [0, 2]},
  // affirmation défavorable (« n'importe qui serait capable de le faire ») : le rouge est du côté « tout à fait d'accord »
  accord5Inverse: {reponses: ["Tout à fait d'accord", "Plutôt d'accord", "Plutôt pas d'accord", "Pas du tout d'accord", "Ne sait pas ou autre"], libelles: ["Tout à fait d’accord", "Plutôt d’accord", "Plutôt pas d’accord", "Pas du tout d’accord", "Ne sait pas ou autre"], couleurs: ["#C24146", "#EBBF95", "#32C2C2", "#007777", "#E0E7EB"], blanc: [0, 3]},
  changements: {reponses: ["Oui, des changements dans le bon sens", "Non, aucun changement", "Oui, des changements dans le mauvais sens", "Ne sait pas ou autre"], couleurs: ["#007777", "#DE9B58", "#C24146", "#E0E7EB"], blanc: [0, 2]},
  impact: {reponses: ["Plutôt positifs", "Les aspects positifs et les aspects négatifs se compensent", "Plutôt négatifs", "Ne sait pas ou autre"], couleurs: ["#007777", "#DE9B58", "#C24146", "#E0E7EB"], blanc: [0, 2]},
  enfreint: {reponses: ["Oui", "Non, mais j’en ai déjà eu envie", "Non, et je n’en jamais eu l’envie", "Ne sait pas ou autre"], libelles: ["Oui", "Non, mais j’en ai déjà eu envie", "Non, et je n’en ai jamais eu l’envie", "Ne sait pas ou autre"], couleurs: ["#C24146", "#DE9B58", "#007777", "#E0E7EB"], blanc: [0, 2]},
};

export const CATALOGUE = [
  {id: "G1", fichier: "G1_bien_etre_travail_general_versant_colonne_barre.svg", largeur: 328, jeu: "bien",
    groupes: [groupe("Bien-être en général", 1, VERSANT, "Versant FP"), groupe("Bien-être au travail", 2, VERSANT, "Versant FP")]},
  {id: "G2", fichier: "G2_bien_etre_general_3dim_colonne_barre.svg", largeur: 328, jeu: "bien",
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Catégorie", 2, CATEGORIE), groupe("Fonctions d’encadrement", 3, ENCADREMENT)]},
  {id: "G3", fichier: "G3_bien_etre_general_croise_travail_colonne_barre.svg", largeur: 328, jeu: "bien",
    groupes: [groupe("Comment vous sentez-vous au travail ?", "", [["Bien"], ["Plutôt bien"], ["Plutôt mal"], ["Mal"]])]},
  {id: "G4", fichier: "G4_bien_etre_travail_3dim_pleine_barre.svg", largeur: 471, jeu: "bien",
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Catégorie", 2, CATEGORIE), groupe("Fonctions d’encadrement", 3, ENCADREMENT)]},
  {id: "G5", fichier: "G5_ambiance_3dim_colonne_barre.svg", largeur: 328, jeu: "bonne",
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Longévité sur le poste", 2, LONGEVITE), groupe("Catégorie", 3, CATEGORIE)]},
  {id: "G6", fichier: "G6_bien_etre_travail_ambiance_colonne_barre.svg", largeur: 328, jeu: "bien",
    groupes: [groupe("Ambiance au travail", "", [["Bonne"], ["Plutôt bonne"], ["Plutôt mauvaise"], ["Mauvaise"]])]},
  {id: "G7", fichier: "G7_soutenabilite_3dim_pleine_barre.svg", largeur: 471, jeu: "oui3",
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Sexe", 2, SEXE), groupe("Catégorie", 3, CATEGORIE)]},
  {id: "G8", fichier: "G8_utile_3dim_colonne_barre.svg", largeur: 328, jeu: "frequence",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Catégorie", 2, CATEGORIE), groupe("Fonctions d’encadrement", 3, ENCADREMENT)]},
  {id: "G10", fichier: "G10_autonomie_competences_pleine_barre.svg", largeur: 471, jeu: "oui5",
    groupes: [groupe("Occasion de développer ses compétences professionnelles", "", [["Tout à fait d'accord", "Tout à fait d’accord"], ["Plutôt d'accord", "Plutôt d’accord"], ["Plutôt pas d'accord", "Plutôt pas d’accord"], ["Pas du tout d'accord", "Pas du tout d’accord"]])]},
  {id: "G11", fichier: "G11_pro_perso_3dim_pleine_barre.svg", largeur: 471, jeu: "oui5",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Fréquence télétravail", 2, TELETRAVAIL), groupe("Fonctions d’encadrement", 3, ENCADREMENT)]},
  // Chapitre 1, données reconstituées depuis les anciens SVG (donnees-extraites/).
  {id: "G12", fichier: "G12_remplacabilite_3dim_pleine_barre.svg", largeur: 471, jeu: "accord5Inverse",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Tranche d’âge", 2, AGE.map(([k, l]) => [l ?? k])), groupe("Catégorie", 3, CATEGORIE)]},
  {id: "G13", fichier: "G13_promotion_2dim_colonne_barre.svg", largeur: 328, jeu: "accord5",
    groupes: [groupe("Longévité sur le poste", 1, LONGEVITE), groupe("Fonctions d’encadrement", 2, ENCADREMENT)]},
  {id: "G14", fichier: "G14_ennui_3dim_large_barre.svg", largeur: 471, jeu: "frequenceNegative",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Catégorie", 2, CATEGORIE), groupe("Fonctions d’encadrement", 3, ENCADREMENT)]},
  {id: "G15", fichier: "G15_sacrifice_qualite_3dim_colonne_barre.svg", largeur: 328, jeu: "frequenceNegative",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Tranche d’âge", 2, AGE.map(([k, l]) => [l ?? k])), groupe("Taille administration", 3, [["100 ou moins"], ["100 à 500"], ["500 à 5000", "500 à 5 000"], ["5000 et plus", "5 000 et plus"]])]},
  {id: "G16", fichier: "G16_interets_particuliers_2dim_pleine_barre.svg", largeur: 471, jeu: "frequenceNegative",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Catégorie", 2, CATEGORIE)]},
  {id: "G18", fichier: "G18_changements_pro_impact_large_barre.svg", largeur: 471, jeu: "impact", groupes: [groupe("Fonctions d’encadrement", "", ENCADREMENT)]},
  // Chapitre 2, données reconstituées.
  {id: "G26", fichier: "G26_collegues_assez_statut_colonne_barre.svg", largeur: 328, jeu: "ouiNon3",
    groupes: [groupe("Statut", "", [["Titulaire ou assimilé"], ["CDD"], ["CDI"], ["Personnel médical hospitalier"], ["Autre"]])]},
  {id: "G29", fichier: "G29_accomp_sugffisant_sexe_stratif_supervision_large_barre.svg", largeur: 471, jeu: "ouiNon3",
    groupes: [groupe("Encadrement / tâche principale", 1, SEXE, "Sexe"), groupe("Encadrement / tâche secondaire", 2, SEXE, "Sexe"), groupe("Pas d’encadrement", 3, SEXE, "Sexe")]},
  // Chapitre 3 et 4, données reconstituées.
  {id: "G47", fichier: "G47_impact_changement_exprimer_maniere_manager_colonne_barre.svg", largeur: 328, jeu: "changements", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G79", fichier: "G79_bien_etre_travail_3dim_vision_desaccord.svg", largeur: 328, jeu: "bien",
    groupes: [groupe("Partage vision SP avec plupart collègues", 1, OUI5), groupe("Partage vision SP avec hiérarchie", 2, OUI5), groupe("Possibilité exprimer désaccord en présence hiérarchie", 3, OUI5)]},
  {id: "G80", fichier: "G80_pleine.svg", largeur: 471, jeu: "bien", colonne: 110, barre: 22,
    groupes: [groupe("Vous recevez des ordres, des consignes, des modes d’emploi. Pour faire votre travail, est-ce que", "", [["Vous appliquez strictement les consignes"], ["Dans certains cas, vous faites autrement"], ["La plupart du temps, vous faites autrement"]])]},
  // Chapitre 2. Hors lot : G40 (indicateur, sans CSV).
  {id: "G19", fichier: "G19_travail_seul_2dim_colonne_barre.svg", largeur: 328, jeu: "frequenceNegative",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Fréquence télétravail", 2, TELETRAVAIL)]},
  {id: "G20", fichier: "G20_ambiance_2dim_large_barre.svg", largeur: 471, jeu: "bonne",
    groupes: [groupe("Travail seul", 1, FREQ4), groupe("Fréquence des réunions d’équipe", 2, REUNIONS)]},
  {id: "G21", fichier: "G21_frequence_reunions_2dim_pleine_barre.svg", largeur: 471, jeu: "reunions",
    groupes: [groupe("Fonctions d’encadrement", 1, ENCADREMENT), groupe("Versant FP", 2, VERSANT)]},
  {id: "G22", fichier: "G22_frequence_convivialite_age_colonne_barre.svg", largeur: 328, jeu: "reunions",
    groupes: [groupe("", 1, AGE)]},
  {id: "G23", fichier: "G23_diffi_hierarchie_versant_colonne_barre.svg", largeur: 328, jeu: "oui5",
    groupes: [groupe("Votre hiérarchie", 1, VERSANT, "Versant FP"), groupe("Vos collègues", 2, VERSANT, "Versant FP")]},
  {id: "G24", fichier: "G24_turnover_equipe_2dim_colonne_barre.svg", largeur: 328, jeu: "turnover",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Catégorie", 2, CATEGORIE)]},
  {id: "G25", fichier: "G25_turnover_equipe_hierarchie_pleine_barre.svg", largeur: 471, jeu: "turnover",
    groupes: [groupe("Comment trouvez-vous le turnover de votre hiérarchie ?", "", TURNOVER)]},
  {id: "G27", fichier: "G27_soutenabilite_collegues_assez_colonne_barre.svg", largeur: 328, jeu: "oui3",
    groupes: [groupe("Collègues en nombre suffisant", "", OUI_NON)]},
  {id: "G28", fichier: "G28_accomp_suffisant_3dim_pleine_barre.svg", largeur: 471, jeu: "ouiNon3",
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Sexe", 2, SEXE), groupe("Turnover équipe", 3, TURNOVER)]},
  {id: "G31", fichier: "G31_apprecie_collegues_3dim_colonne_barre.svg", largeur: 328, jeu: "oui5",
    groupes: [groupe("Accompagnement suffisant", 1, OUI_NON), groupe("Turnover équipe", 2, TURNOVER), groupe("Collègues en nombre suffisant", 3, OUI_NON)]},
  {id: "G32", fichier: "G32_concurrence_collegues_3dim_colonne_barre.svg", largeur: 328, jeu: "nonOui2",
    groupes: [groupe("Accompagnement suffisant", 1, OUI_NON), groupe("Turnover équipe", 2, TURNOVER), groupe("Collègues en nombre suffisant", 3, OUI_NON)]},
  {id: "G33", fichier: "G33_vision_SP_collegues_3dim_pleine_barre.svg", largeur: 471, jeu: "oui5",
    groupes: [groupe("Accompagnement suffisant", 1, OUI_NON), groupe("Turnover équipe", 2, TURNOVER), groupe("Collègues en nombre suffisant", 3, OUI_NON)]},
  {id: "G34", fichier: "G34_apprecie_collegues_abc_colonne_barre.svg", largeur: 328, jeu: "oui5",
    groupes: [groupe("Catégorie", 1, CATEGORIE)]},
  {id: "G35", fichier: "G35_apprecie_collegues_abc_stratif_versant_pleine_barre.svg", largeur: 471, jeu: "oui5",
    groupes: [groupe("FPE", 1, CATEGORIE, "Catégorie"), groupe("FPT", 2, CATEGORIE, "Catégorie"), groupe("FPH", 3, CATEGORIE, "Catégorie")]},
  {id: "G36", fichier: "G36_concurrence_collegues_abc_stratif_versant_large_barre.svg", largeur: 382, jeu: "nonOui2", barre: 10.5,
    groupes: [groupe("FPE", 1, CATEGORIE, "Catégorie"), groupe("FPT", 2, CATEGORIE, "Catégorie"), groupe("FPH", 3, CATEGORIE, "Catégorie")]},
  {id: "G37", fichier: "G37_vision_SP_collegues_4dim_large_barre.svg", largeur: 366, jeu: "oui5", barre: 12,
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Versant FP", 2, VERSANT), groupe("Fonctions d’encadrement", 3, ENCADREMENT), groupe("Catégorie", 4, CATEGORIE)]},
  {id: "G38", fichier: "G38_vision_SP_hierarchie_4dim_pleine_barre.svg", largeur: 471, jeu: "oui5",
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Versant FP", 2, VERSANT), groupe("Fonctions d’encadrement", 3, ENCADREMENT), groupe("Catégorie", 4, CATEGORIE)]},
  {id: "G39", fichier: "G39_bien_etre_travail_3dim_special_pleine_barre.svg", largeur: 471, jeu: "bien",
    groupes: [groupe("Apprécie relations avec collègues", 1, OUI5), groupe("Concurrence collègues équipe", 2, [["Non"], ["Oui"]]), groupe("Partage vision SP avec plupart collègues", 3, OUI5)]},
  // Chapitre 3. Hors lot : G30, G45, G46, G47, G66 (CSV vides, réponses multiples ou parts de réponses positives).
  {id: "G41", fichier: "G41_ident_resp_2dim_colonne_barre.svg", largeur: 328, jeu: "identification",
    groupes: [groupe("Catégorie", 1, CATEGORIE), groupe("Versant FP", 2, VERSANT)]},
  {id: "G42", fichier: "G42_indications_abc_large_barre.svg", largeur: 362, jeu: "indications", groupes: [groupe("Catégorie", "", CATEGORIE)]},
  {id: "G43", fichier: "G43_resp_consignes_abc_colonne_barre.svg", largeur: 362, jeu: "consignes", groupes: [groupe("Catégorie", "", CATEGORIE)]},
  {id: "G44", fichier: "G44_entretien_pro_abc_colonne_barre.svg", largeur: 340, jeu: "ouiNon3", groupes: [groupe("Catégorie", "", CATEGORIE)]},
  {id: "G48", fichier: "G48_managers_leviers_expertise_qlte_vie_versant_pleine_barre.svg", largeur: 471, jeu: "accord5",
    groupes: [groupe("Leviers pour reconnaître et valoriser expertise", 1, VERSANT, "Versant FP"), groupe("Leviers pour améliorer qualité de vie au travail personnes encadrées", 2, VERSANT, "Versant FP")]},
  {id: "G49", fichier: "G49_managers_eval_2dim_colonne_barre.svg", largeur: 328, jeu: "ouiToutAFait",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Fonctions d’encadrement", 2, ENCADRANTS)]},
  {id: "G50", fichier: "G50_managers_promo_2dim_colonne_barre.svg", largeur: 328, jeu: "ouiToutAFait",
    groupes: [groupe("Versant FP", 1, VERSANT), groupe("Fonctions d’encadrement", 2, ENCADRANTS)]},
  {id: "G51", fichier: "G51_managers_bien_etre_travail_2dim_colonne_barre.svg", largeur: 328, jeu: "bien",
    groupes: [groupe("…prend le temps de discuter", 1, ACCORD4), groupe("…prête attention à ce que je dis", 2, ACCORD4)]},
  {id: "G52", fichier: "G52_exprim_abc_colonne_barre.svg", largeur: 328, jeu: "accord5", groupes: [groupe("Catégorie", "", CATEGORIE)]},
  {id: "G53", fichier: "G53_attention_bienetre_versant_colonne_barre.svg", largeur: 328, jeu: "accord5", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G54", fichier: "G54_bien_etre_travail_equilibre_large_barre.svg", largeur: 361, jeu: "bien",
    groupes: [groupe("Supérieur·e veille à l’équilibre de la charge de travail", "", ACCORD4)]},
  {id: "G55", fichier: "G55_managers_regul_versant_colonne_barre.svg", largeur: 328, jeu: "accord5", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G56", fichier: "G56_ambiance_versant_large_barre.svg", largeur: 471, jeu: "bonne",
    groupes: [groupe("Supérieur·e valorise expertise", "", ACCORD4)]},
  {id: "G57", fichier: "G57_estime_supervision_large_barre.svg", largeur: 471, jeu: "accord5", groupes: [groupe("Fonctions d’encadrement", "", ENCADREMENT)]},
  {id: "G58", fichier: "G58_managers_echanges_reguliers_supervision_large_barre.svg", largeur: 471, jeu: "accord5", groupes: [groupe("Fonctions d’encadrement", "", ENCADRANTS)]},
  {id: "G59", fichier: "G59_discut_supervision_pleine_barre.svg", largeur: 471, jeu: "accord5", groupes: [groupe("Fonctions d’encadrement", "", ENCADREMENT)]},
  {id: "G60", fichier: "G60_managers_connais_versant_colonne_barre.svg", largeur: 471, jeu: "accord5", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G61", fichier: "G61_eval_connais_versant_colonne_barre.svg", largeur: 265, jeu: "accord5", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G62", fichier: "G62_managers_transm_info_versant_colonne_barre.svg", largeur: 290, jeu: "accord5", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G63", fichier: "G63_reponses_versant_colonne_barre.svg", largeur: 290, jeu: "accord5", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G64", fichier: "G64_managers_bien_etre_travail_cause_pleine_barre.svg", largeur: 471, jeu: "bien", colonne: 150, barre: 40,
    groupes: [groupe("Votre positionnement en tant que manager est-il le résultat… ?", "", CAUSES_MANAGER)]},
  {id: "G65", fichier: "G65_accomp_suffisant_accomp_seul_colonne_barre.svg", largeur: 328, jeu: "ouiNon3",
    groupes: [groupe("Déclare s’être débrouillé·e seul·e lors de la prise de poste", "", OUI_NON)]},
  {id: "G67", fichier: "G67_managers_benefice_accompagnement_court_colonne_barre.svg", largeur: 328, jeu: "ouiNon2", colonne: 110, barre: 40,
    groupes: [groupe("Origine de la position de manager", "", CAUSES_MANAGER)]},
  {id: "G68", fichier: "G68_managers_dvlp_competences_benefice_accomp_colonne_barre.svg", largeur: 328, jeu: "accord5",
    groupes: [groupe("Bénéfice d’au moins une forme d’accompagnement (formations management, échanges avec pairs, kits, autre)", "", OUI_NON)]},
  {id: "G69", fichier: "G69_managers_estime_benefice_accomp_pleine_barre.svg", largeur: 471, jeu: "accord5",
    groupes: [groupe("Bénéfice d’au moins une forme d’accompagnement (formations management, échanges avec pairs, kits, autre)", "", OUI_NON)]},
  // Chapitre 4. Hors lot : G78 (écart importance/agir), G79 et G80 (sans CSV).
  {id: "G70", fichier: "G70_impt_equite_2dim_large_barre.svg", largeur: 340, jeu: "importance", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G71", fichier: "G71_impt_argent_public_2dim_large_barre.svg", largeur: 340, jeu: "importance", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G72", fichier: "G72_impt_lois_reglements_2dim_large_barre.svg", largeur: 340, jeu: "importance", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G73", fichier: "G73_impt_ineg_2dim_large_barre.svg", largeur: 340, jeu: "importance", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G74", fichier: "G74_agir_equite_2dim_large_barre.svg", largeur: 340, jeu: "oui5", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G75", fichier: "G75_agir_argent_public_2dim_colonne_barre.svg", largeur: 340, jeu: "oui5", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G76", fichier: "G76_agir_lois_reglements_2dim_large_barre.svg", largeur: 340, jeu: "oui5", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G77", fichier: "G77_agir_ineg_2dim_large_barre.svg", largeur: 340, jeu: "oui5", groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Niveau de diplôme", 2, DIPLOME)]},
  {id: "G81", fichier: "G81_desaccord_collegues_3dim_colonne_barre.svg", largeur: 352, jeu: "oui5", barre: 12,
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Sexe", 2, SEXE), groupe("Niveau de diplôme", 3, DIPLOME)]},
  {id: "G82", fichier: "G82_desaccord_hierarchie_3dim_colonne_barre.svg", largeur: 352, jeu: "oui5", barre: 12,
    groupes: [groupe("Tranche d’âge", 1, AGE), groupe("Sexe", 2, SEXE), groupe("Niveau de diplôme", 3, DIPLOME)]},
  {id: "G83", fichier: "G83_managers_degrad_bien_etre_travail_colonne_barre.svg", largeur: 314, jeu: "degradation",
    groupes: [groupe("Comment vous sentez-vous au travail ?", "", [["Bien"], ["Plutôt bien"], ["Plutôt mal"], ["Mal"]])]},
  {id: "G84", fichier: "G84_managers_degrad_versant_colonne_barre.svg", largeur: 314, jeu: "degradation", groupes: [groupe("Versant FP", "", VERSANT)]},
  {id: "G85", fichier: "G85_managers_transmission_consignes_versant_pleine_barre.svg", largeur: 471, jeu: "transmission",
    groupes: [groupe("Refuser de les transmettre", 1, VERSANT, "Versant FP"), groupe("Transmettre après avoir manifesté votre désaccord", 2, VERSANT, "Versant FP"), groupe("Transmettre sans manifester de désaccord", 3, VERSANT, "Versant FP")]},
  {id: "G86", fichier: "G86_enfreindre_3dim_colonne_barre.svg", largeur: 328, jeu: "ouiNon3",
    groupes: [groupe("Sexe", 1, SEXE), groupe("Niveau de diplôme", 2, DIPLOME), groupe("Versant FP", 3, VERSANT)]},
  {id: "G87", fichier: "G87_deja_enfreint_3dim_pleine_barre.svg", largeur: 471, jeu: "enfreint",
    groupes: [groupe("Sexe", 1, SEXE), groupe("Niveau de diplôme", 2, DIPLOME), groupe("Versant FP", 3, VERSANT)]},
  {id: "G88", fichier: "G88_deja_enfreint_2dim_pleine_barre.svg", largeur: 471, jeu: "enfreint",
    groupes: [groupe("Possibilité d’exprimer un désaccord en présence de sa hiérarchie", 1, OUI5), groupe("Est-il de votre devoir d’enfreindre des ordres dans certaines circonstances ?", 2, OUI_NON)]},
  {id: "G89", fichier: "G89_enfreindre_sacrif_colonne_barre.svg", largeur: 328, jeu: "ouiNon3",
    groupes: [groupe("Sacrifice qualité du travail", "", FREQ4)]},
  {id: "G90", fichier: "G90_managers_enfreindre_degrad_colonne_barre.svg", largeur: 328, jeu: "ouiNon3",
    groupes: [groupe("Avoir reçu consignes supérieur·es dégradant le sens au travail des agent·es", "", [["Oui, très fréquemment"], ["Oui, souvent"], ["Oui, parfois"], ["Non, jamais"]])]},
  {id: "G91", fichier: "G91_bien_etre_travail_enfreindre_deja_enfreint_pleine_barre.svg", largeur: 471, jeu: "bien",
    groupes: [groupe("Dans certaines circonstances, pensez-vous qu’il serait de votre devoir d’enfreindre des ordres hiérarchiques ?", 1, OUI_NON), groupe("Vous est-il déjà arrivé d’enfreindre un ordre hiérarchique ?", 2, [["Oui"], ["Non, mais j’en ai déjà eu envie"], ["Non, et je n’en jamais eu l’envie", "Non, et je n’en ai jamais eu l’envie"]])]},
];
